
title: 中国社会民族主义论坛
email: your-email@example.com
description: >- # 此处可填写论坛简介
  一个致力于讨论中国社会民族主义的论坛。
baseurl: "" # 站点子路径，若部署到根目录可留空
url: "https://daniek0617.github.io" # 部署网址

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM

collections:
  posts:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "管理员"

permalink: /:categories/:year/:month/:day/:title.html
