title: 中国社会民族主义论坛
description: 聚焦现实、批判修正、反对形式、追求真正服务人民的意识形态理论探讨。
url: ""  # 部署后添加你的网址
baseurl: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: ""
giscus:
  repo: daniek0617/sheminzuluntan.vip
  repo_id: YOUR_REPO_ID
  category: Announcements
  category_id: YOUR_CATEGORY_ID
  mapping: pathname
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: light
  lang: zh-CN